{
 "title": "Traefik v2.0 Metrics",
 "description": "Traefik v2 metrics from Influxdb database originally from floriantales (dashboard 10479)",
 "tags": [
  "www",
  "influxdb",
  "traefik v2"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "backend",
    "label": "Backend",
    "query": "select * from \"traefik.backend.requests.total\""
   },
   { "name": "sampling", "label": "Sampling", "query": "1m,5m,10m,30m,60m" }
  ]
 },
 "panels": [
  {
   "title": "EntryPoint Request",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "traefik.entrypoint.requests.total",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total status code count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_code",
     "groupBy": [
      { "params": [ "code" ], "type": "tag" }
     ],
     "measurement": "traefik.service.requests.total",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_backend",
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "backend" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "traefik.service.request.duration",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service Requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "traefik.service.requests.total",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_code",
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "code" ], "type": "tag" }
     ],
     "measurement": "traefik.service.requests.total",
     "query": "SELECT sum(\"count\") FROM \"traefik.backend.requests.total\" WHERE $timeFilter GROUP BY time($__interval), \"backend\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}